default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        exclude: ^docs/

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^docs/

  - repo: https://github.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-broken-line==0.4.0
          - flake8-builtins==1.5.3
          - flake8-bugbear==22.3.23
          - flake8-comprehensions==3.8.0
          - flake8-eradicate==1.2.0
          - flake8-pep3101==1.3.0
          - flake8-print==4.0.0
          - flake8-quotes==3.3.1
          - flake8-logging-format==0.9.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
        exclude: ^demand_sensing/feature_engine/tests/dummy_json_output/
      - id: pretty-format-json
        types: [json]
        exclude: ^demand_sensing/feature_engine/tests/dummy_json_output/
        args: [--autofix, --no-sort-keys, --indent=4]
      - id: check-toml
      - id: check-yaml
        exclude: 'template.*\.yaml$'

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.24.0
    hooks:
      - id: check-jsonschema
        files: ^demand_sensing/common/schemas/.*\.json$|^ais_pulse/app/config/.*schema\.json$
        args: [--schemafile, demand_sensing/common/config/meta_schema.json]
